apiVersion: v1
kind: Secret
metadata:
  name: cube
type: Opaque
stringData:
  default_prefix: "c!"
  redis_addr: <redis_addr here>
  redis_password: <redis_password here>
  discord_token: <discord_token here>
  sentry_dsn: <sentry_dsn here>
